Traceback (most recent call last):
  File "/home/txmack713/Desktop/GitHub/it_automation_python/bash_scripting/./streams_err.py", line 7, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
